#!/usr/bin/env python3
import argparse, shutil, os, subprocess, sys
from pathlib import Path

def copytree_merge(src, dst):
    if not src.exists(): return
    for p in src.rglob("*"):
        rel=p.relative_to(src)
        out=dst/rel
        if p.is_dir():
            out.mkdir(parents=True, exist_ok=True)
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            if not out.exists():
                shutil.copy2(p,out)

def write_adapter(target, adapter):
    marker="<!-- AppForger generated adapter -->\n"
    content=marker+"# AppForger\n\nRead `project-control/APPFORGE_ACTIVE_RULES.md` and follow AppForger source-of-truth rules.\n"
    if adapter=="codex":
        (target/"AGENTS.md").write_text(content,encoding="utf-8")
    elif adapter=="claude":
        (target/"CLAUDE.md").write_text(content,encoding="utf-8")
    elif adapter=="cursor":
        p=target/".cursor/rules/appforge.mdc"; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(content,encoding="utf-8")
    elif adapter=="copilot":
        p=target/".github/copilot-instructions.md"; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(content,encoding="utf-8")

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--target", default=".")
    ap.add_argument("--name", default="AppForger Project")
    ap.add_argument("--agent-adapters", default="")
    ap.add_argument("--project-state", default="ask")
    ap.add_argument("--app-type", default="ask")
    ap.add_argument("--backend", default="ask")
    ap.add_argument("--init-local-runtime-env", action="store_true")
    args=ap.parse_args()
    target=Path(args.target).resolve()
    engine=Path(__file__).resolve().parents[3]
    tmpl=engine/"templates/engine"
    copytree_merge(tmpl/"project-control-template", target/"project-control")
    copytree_merge(tmpl/"workspace-template", target)
    for d in ["docs","design-assets","exports","local-only"]:
        (target/d).mkdir(exist_ok=True)
    env_ex=target/"local-only/.env.local.example"
    env=target/"local-only/.env.local"
    if env_ex.exists() and not env.exists():
        shutil.copy2(env_ex, env)
    (target/"project-control/APPFORGE_ACTIVE_RULES.md").write_text("# AppForger Active Rules\n\nGenerated by setup.\n",encoding="utf-8")
    adapters=[a.strip() for a in args.agent_adapters.split(",") if a.strip()]
    if "all" in adapters:
        adapters=["codex","claude","cursor","copilot"]
    for a in adapters:
        write_adapter(target,a)
    (target/"APPFORGE_INJECTION_SUMMARY.md").write_text(f"# AppForger Injection Summary\n\nProject: {args.name}\nAdapters: {', '.join(adapters) or 'none'}\n",encoding="utf-8")
    print(f"AppForger workspace prepared at {target}")
    print("Fill local-only/.env.local next.")
if __name__=="__main__": main()
